name: Compile Linux AppImage
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install Linux C Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpv-dev fuse

      - name: Nuitka Compile (Linux Standalone)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/estia.py
          mode: standalone
          include-package: mpv
          include-data-files: /usr/lib/x86_64-linux-gnu/libmpv.so=libmpv.so

      - name: Structure & Package AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          
          cp -r build/estia.dist/* AppDir/usr/bin/
          ln -s usr/bin/estia AppDir/AppRun
          
          cat <<EOF > AppDir/estia.desktop
          [Desktop Entry]
          Name=Estia
          Exec=AppRun
          Icon=estia
          Type=Application
          Categories=Utility;
          EOF
          
          cp icon.png AppDir/estia.png
          cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/estia.png
          
          curl -L -o appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool
          ./appimagetool --appimage-extract
          ./squashfs-root/AppRun AppDir Estia-x86_64.AppImage

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: estia-linux-appimage
          path: Estia-x86_64.AppImage
